QUE.1)
ANS-->


In [2]:
import numpy as np
np.arange(start=2,stop=50,step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

QUE.2)
ANS-->

In [17]:
import numpy as np
lst1=[]
lst2=[]
n=int(input("Enter number of element"))
for i in range(0,n):
    ele1=int(input())
    lst1.append(ele1)
for j in range(0,n):
    ele2=int(input())
    lst2.append(ele2)
array1=np.array(lst1)
array2=np.array(lst2)
appended=[y for x in [array1,array2] for y in x]
print(str(appended))
arr=np.sort(array1)
brr=np.sort(array2)
print(arr)
print(brr)

Enter number of element3
5
4
3
8
4
3
[5, 4, 3, 8, 4, 3]
[3 4 5]
[3 4 8]


QUE.3)
ANS-->


In [19]:
import numpy as np
arr=np.array([[4,2,7,8],[9,6,8,7]])
print("Dimensions:",arr.ndim)
print("Size:",arr.size)

Dimensions: 2
Size: 8


QUE.4
ANS-->

In [20]:
a=np.array([1,2,3,4,5])
a.shape

(5,)

In [21]:
b=np.expand_dims(a,axis=1)
b.shape

(5, 1)

In [22]:
c=np.expand_dims(a,axis=0)
c.shape

(1, 5)

QUE.5
ANS-->


In [24]:
a=np.array([[2,4],[3,5]])
b=np.array([[7,9],[6,8]])
#vertical stacking
print("vertical stacking:\n",np.vstack((a,b)))
#horizontal stacking
print("horizontal stacking:\n",np.hstack((a,b)))

vertical stacking:
 [[2 4]
 [3 5]
 [7 9]
 [6 8]]
horizontal stacking:
 [[2 4 7 9]
 [3 5 6 8]]


QUE.6
ANS-->


In [25]:
# input list
items=[3,7,8,9,6,6,4,3,3,7]
#get items
l1=[]
#counter
count=0
for item in items:
    if item not in l1:
        count+=1
        l1.append(item)
#printing no of unique items from input list
print("No of unique items:",count)



No of unique items: 6
